var gPlantData=[
	{id:"apple",name:"Apple",latin:"",note:"Hmm, Apple, what a charmer!"},
	{id:"apricot",name:"Apricot",latin:"",note:"Hmm, Apricot, what a charmer!"},
	{id:"asparagus",name:"Asparagus",latin:"",note:"Hmm, Asparagus, what a charmer!"},
	{id:"basil",name:"Basil",latin:"",note:"Hmm, Basil, what a charmer!"},
	{id:"beans",name:"Beans",latin:"",note:"Hmm, Beans, what a charmer!"},
	{id:"broad_beans",name:"Broad Beans",latin:"",note:"Hmm, Broad Beans, what a charmer!"},
	{id:"bush_beans",name:"Bush Beans",latin:"",note:"Hmm, Bush Beans, what a charmer!"},
	{id:"climbing_beans",name:"Climbing Beans",latin:"",note:"Hmm, Climbing Beans, what a charmer!"},
	{id:"beets",name:"Beets",latin:"",note:"Hmm, Beets, what a charmer!"},
	{id:"borage",name:"Borage",latin:"",note:"Hmm, Borage, what a charmer!"},
	{id:"broccoli",name:"Broccoli",latin:"",note:"Hmm, Broccoli, what a charmer!"},
	{id:"brussell_sprouts",name:"Brussell Sprouts",latin:"",note:"Hmm, Brussell Sprouts, what a charmer!"},
	{id:"cabbages",name:"Cabbages",latin:"",note:"Hmm, Cabbages, what a charmer!"},
	{id:"chamomile",name:"Chamomile",latin:"",note:"Hmm, Chamomile, what a charmer!"},
	{id:"carrots",name:"Carrots",latin:"",note:"Hmm, Carrots, what a charmer!"},
	{id:"cauliflower",name:"Cauliflower",latin:"",note:"Hmm, Cauliflower, what a charmer!"},
	{id:"celery",name:"Celery",latin:"",note:"Hmm, Celery, what a charmer!"},
	{id:"cherry",name:"Cherry",latin:"",note:"Hmm, Cherry, what a charmer!"},
	{id:"chervil",name:"Chervil",latin:"",note:"Hmm, Chervil, what a charmer!"},
	{id:"chives",name:"Chives",latin:"",note:"Hmm, Chives, what a charmer!"},
	{id:"coriander_dill",name:"Coriander_Dill",latin:"",note:"Hmm, Coriander/Dill, what a charmer!"},
	{id:"corn",name:"Corn",latin:"",note:"Hmm, Corn, what a charmer!"},
	{id:"cucumber",name:"Cucumber",latin:"",note:"Hmm, Cucumber, what a charmer!"},
	{id:"fennel",name:"Fennel",latin:"",note:"Hmm, Fennel, what a charmer!"},
	{id:"marigold",name:"Marigold",latin:"",note:"Hmm, Marigold, what a charmer!"},
	{id:"fruit_trees",name:"Fruit Trees",latin:"",note:"Hmm, Fruit Trees, what a charmer!"},
	{id:"garlic",name:"Garlic",latin:"",note:"Hmm, Garlic, what a charmer!"},
	{id:"grape_vine",name:"Grape Vine",latin:"",note:"Hmm, Grape Vine, what a charmer!"},
	{id:"lettuce",name:"Lettuce",latin:"",note:"Woah there, Lettuce is popular!"},
	{id:"marjoram",name:"Marjoram",latin:"",note:"Hmm, Marjoram, what a charmer!"},
	{id:"mulberry",name:"Mulberry",latin:"",note:"Hmm, Mulberry, what a charmer!"},
	{id:"nasturtium",name:"Nasturtium",latin:"",note:"Hmm, Nasturtium, what a charmer!"},
	{id:"onions",name:"Onions",latin:"",note:"Hmm, Onions, what a charmer!"},
	{id:"parsley",name:"Parsley",latin:"",note:"Hmm, Parsley, what a charmer!"},
	{id:"peas",name:"Peas",latin:"",note:"Hmm, Peas, what a charmer!"},
	{id:"pennyroyal",name:"Pennyroyal",latin:"",note:"Hmm, Pennyroyal, what a charmer!"},
	{id:"potatoes",name:"Potatoes",latin:"",note:"Hmm, Potatoes, what a charmer!"},
	{id:"pumpkin",name:"Pumpkin",latin:"",note:"Hmm, Pumpkin, what a charmer!"},
	{id:"radish",name:"Radish",latin:"",note:"Hmm, Radish, what a charmer!"},
	{id:"rosemary",name:"Rosemary",latin:"",note:"Hmm, Rosemary, what a charmer!"},
	{id:"roses",name:"Roses",latin:"",note:"Hmm, Roses, what a charmer!"},
	{id:"rue",name:"Rue",latin:"",note:"Hmm, Rue, what a charmer!"},
	{id:"sage",name:"Sage",latin:"",note:"Hmm, Sage, what a charmer!"},
	{id:"savory",name:"Savory",latin:"",note:"Hmm, Savory, what a charmer!"},
	{id:"silverbeet",name:"Silverbeet",latin:"",note:"Hmm, Silverbeet, what a charmer!"},
	{id:"spinach",name:"Spinach",latin:"",note:"Hmm, Spinach, what a charmer!"},
	{id:"squash",name:"Squash",latin:"",note:"Hmm, Squash, what a charmer!"},
	{id:"strawberry",name:"Strawberry",latin:"",note:"Hmm, Strawberry, what a charmer!"},
	{id:"stinging_nettle",name:"Stinging Nettle",latin:"",note:"Hmm, Stinging Nettle, what a charmer!"},
	{id:"sunflower",name:"Sunflower",latin:"",note:"Hmm, Sunflower, what a charmer!"},
	{id:"tomato",name:"Tomato",latin:"",note:"Hmm, Tomato, what a charmer!"},
	{id:"yarrow",name:"Yarrow",latin:"",note:"Hmm, Yarrow, what a charmer!"},
	{id:"zucchini",name:"Zucchini",latin:"",note:"Hmm Zucchini, what a charmer!"},
	{id:"horseradish",name:"Horseradish",latin:"",note:"Hmm Horseradish, what a charmer!"},
	{id:"grass",name:"Grass",latin:"",note:"Hmm Grass, what a charmer!"},
	{id:"lemon_balm",name:"Lemon Balm",latin:"",note:"Hmm Lemon Balm, what a charmer!"},
	{id:"mustard",name:"Mustard",latin:"",note:"Hmm Mustard, what a charmer!"},
	{id:"eggplant",name:"Eggplant",latin:"",note:"Hmm Eggplant, what a charmer!"},
	{id:"thyme",name:"Thyme",latin:"",note:"Hmm Thyme, what a charmer!"},
	{id:"leeks",name:"Leeks",latin:"",note:"Hmm Leeks, what a charmer!"},
	{id:"parsnip",name:"Parsnip",latin:"",note:"Hmm Parsnip, what a charmer!"},
	{id:"lavender",name:"Lavender",latin:"",note:"Hmm Lavender, what a charmer!"},
	{id:"mints",name:"Mints",latin:"",note:"Hmm Mints, what a charmer!"},
	{id:"rose",name:"Rose",latin:"",note:"Hmm Rose, what a charmer!"},
	{id:"raspberry",name:"raspberry",latin:"",note:"Hmm raspberry, what a charmer!"},
	{id:"sliverbeet",name:"sliverbeet",latin:"",note:"Hmm sliverbeet, what a charmer!"},
	{id:"gooseberry",name:"gooseberry",latin:"",note:"Hmm gooseberry, what a charmer!"}
];



var gRelationsData=[

	{plant1:"apple",plant2:"chives",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"apple",plant2:"marigold",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"apple",plant2:"garlic",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"apple",plant2:"horseradish",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"apple",plant2:"lemon_balm",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"apple",plant2:"mustard",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"apple",plant2:"nasturtium",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"apple",plant2:"spinach",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"apple",plant2:"yarrow",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"apricot",plant2:"basil",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"apricot",plant2:"marigold",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"apricot",plant2:"garlic",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"apricot",plant2:"nasturtium",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"apricot",plant2:"spinach",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"apricot",plant2:"stinging_nettle",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"apricot",plant2:"sunflower",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"apricot",plant2:"tomato",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"apricot",plant2:"yarrow",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"asparagus",plant2:"basil",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"asparagus",plant2:"marjoram",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"asparagus",plant2:"parsley",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"asparagus",plant2:"tomato",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"basil",plant2:"apricot",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"basil",plant2:"asparagus",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"basil",plant2:"chives",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"basil",plant2:"cucumber",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"basil",plant2:"fennel",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"basil",plant2:"rue",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"basil",plant2:"tomato",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"broccoli",plant2:"beans",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"brussell_sprouts",plant2:"beans",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"beans",plant2:"cabbages",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"beans",plant2:"carrots",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cauliflower",plant2:"beans",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"beans",plant2:"chives",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"beans",plant2:"corn",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"beans",plant2:"cucumber",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"beans",plant2:"fennel",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"beans",plant2:"marigold",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"beans",plant2:"garlic",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"beans",plant2:"grape_vine",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"beans",plant2:"lettuce",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"beans",plant2:"marjoram",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"beans",plant2:"onions",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"beans",plant2:"parsley",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"peas",plant2:"beans",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"beans",plant2:"potatoes",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"beans",plant2:"rosemary",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"beans",plant2:"sage",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"beans",plant2:"savory",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"broad_beans",plant2:"bush_beans",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"broccoli",plant2:"broad_beans",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"brussell_sprouts",plant2:"broad_beans",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"broad_beans",plant2:"cabbages",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cauliflower",plant2:"broad_beans",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"broad_beans",plant2:"chives",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"broad_beans",plant2:"corn",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"broad_beans",plant2:"fennel",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"broad_beans",plant2:"garlic",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"broad_beans",plant2:"lettuce",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"broad_beans",plant2:"marjoram",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"broad_beans",plant2:"onions",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"broad_beans",plant2:"potatoes",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"broad_beans",plant2:"spinach",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"bush_beans",plant2:"climbing_beans",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"broccoli",plant2:"bush_beans",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"brussell_sprouts",plant2:"bush_beans",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"bush_beans",plant2:"cabbages",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cauliflower",plant2:"bush_beans",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"bush_beans",plant2:"celery",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"bush_beans",plant2:"chives",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"bush_beans",plant2:"corn",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"bush_beans",plant2:"cucumber",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"bush_beans",plant2:"garlic",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"bush_beans",plant2:"marjoram",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"bush_beans",plant2:"onions",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"bush_beans",plant2:"potatoes",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"bush_beans",plant2:"strawberry",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"bush_beans",plant2:"sunflower",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"climbing_beans",plant2:"climbing_beans",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"broccoli",plant2:"climbing_beans",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"brussell_sprouts",plant2:"climbing_beans",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"climbing_beans",plant2:"cabbages",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cauliflower",plant2:"climbing_beans",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"climbing_beans",plant2:"chives",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"climbing_beans",plant2:"corn",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"climbing_beans",plant2:"garlic",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"climbing_beans",plant2:"lettuce",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"climbing_beans",plant2:"marjoram",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"climbing_beans",plant2:"onions",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"climbing_beans",plant2:"radish",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"climbing_beans",plant2:"sunflower",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"beets",plant2:"broad_beans",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"beets",plant2:"bush_beans",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"broccoli",plant2:"beets",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"brussell_sprouts",plant2:"beets",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"beets",plant2:"cabbages",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cauliflower",plant2:"beets",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"beets",plant2:"lettuce",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"beets",plant2:"marjoram",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"beets",plant2:"onions",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"beets",plant2:"potatoes",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"beets",plant2:"sliverbeet",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"beets",plant2:"tomato",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"broccoli",plant2:"borage",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"brussell_sprouts",plant2:"borage",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"borage",plant2:"cabbages",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cauliflower",plant2:"borage",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"borage",plant2:"cucumber",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"peas",plant2:"borage",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"borage",plant2:"squash",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"borage",plant2:"strawberry",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"borage",plant2:"tomato",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cabbages",plant2:"beans",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cabbages",plant2:"broad_beans",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cabbages",plant2:"bush_beans",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cabbages",plant2:"climbing_beans",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cabbages",plant2:"beets",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cabbages",plant2:"borage",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cabbages",plant2:"chamomile",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cabbages",plant2:"celery",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cabbages",plant2:"coriander_dill",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cabbages",plant2:"cucumber",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cabbages",plant2:"marigold",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cabbages",plant2:"garlic",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cabbages",plant2:"lettuce",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cabbages",plant2:"marjoram",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cabbages",plant2:"nasturtium",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cabbages",plant2:"onions",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"peas",plant2:"cabbages",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cabbages",plant2:"pennyroyal",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cabbages",plant2:"potatoes",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cabbages",plant2:"rosemary",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cabbages",plant2:"rue",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cabbages",plant2:"sage",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cabbages",plant2:"strawberry",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cabbages",plant2:"tomato",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"carrots",plant2:"beans",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"carrots",plant2:"chives",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"carrots",plant2:"coriander_dill",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"carrots",plant2:"cucumber",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"carrots",plant2:"marigold",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"carrots",plant2:"lettuce",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"carrots",plant2:"marjoram",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"carrots",plant2:"onions",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"peas",plant2:"carrots",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"carrots",plant2:"radish",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"carrots",plant2:"rosemary",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"carrots",plant2:"sage",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"carrots",plant2:"tomato",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"celery",plant2:"climbing_beans",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"celery",plant2:"cabbages",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cauliflower",plant2:"celery",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"celery",plant2:"marjoram",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"peas",plant2:"celery",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"celery",plant2:"potatoes",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"celery",plant2:"tomato",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cherry",plant2:"chives",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cherry",plant2:"marigold",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cherry",plant2:"lettuce",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cherry",plant2:"nasturtium",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cherry",plant2:"potatoes",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cherry",plant2:"sliverbeet",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cherry",plant2:"spinach",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"chervil",plant2:"coriander_dill",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"chervil",plant2:"garlic",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"chervil",plant2:"lettuce",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"chervil",plant2:"parsley",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"chervil",plant2:"radish",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"chervil",plant2:"yarrow",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"chives",plant2:"apple",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"chives",plant2:"asparagus",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"chives",plant2:"beans",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"chives",plant2:"broad_beans",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"chives",plant2:"bush_beans",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"chives",plant2:"climbing_beans",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"chives",plant2:"carrots",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"chives",plant2:"cherry",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"chives",plant2:"fruit_trees",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"chives",plant2:"marjoram",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"chives",plant2:"mulberry",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"peas",plant2:"chives",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"chives",plant2:"rose",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"chives",plant2:"strawberry",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"chives",plant2:"tomato",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"broccoli",plant2:"coriander_dill",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"brussell_sprouts",plant2:"coriander_dill",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"coriander_dill",plant2:"cabbages",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"coriander_dill",plant2:"carrots",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cauliflower",plant2:"coriander_dill",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"coriander_dill",plant2:"chervil",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"coriander_dill",plant2:"fennel",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"corn",plant2:"beans",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"corn",plant2:"broad_beans",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"corn",plant2:"bush_beans",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"corn",plant2:"climbing_beans",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"corn",plant2:"cucumber",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"corn",plant2:"marjoram",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"peas",plant2:"corn",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"corn",plant2:"potatoes",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"corn",plant2:"pumpkin",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"corn",plant2:"radish",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"corn",plant2:"squash",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"corn",plant2:"zucchini",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cucumber",plant2:"basil",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cucumber",plant2:"beans",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cucumber",plant2:"bush_beans",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cucumber",plant2:"borage",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"broccoli",plant2:"cucumber",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"brussell_sprouts",plant2:"cucumber",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cucumber",plant2:"cabbages",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cucumber",plant2:"carrots",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cauliflower",plant2:"cucumber",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cucumber",plant2:"corn",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cucumber",plant2:"lettuce",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cucumber",plant2:"marjoram",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cucumber",plant2:"nasturtium",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"peas",plant2:"cucumber",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cucumber",plant2:"potatoes",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cucumber",plant2:"radish",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cucumber",plant2:"sage",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cucumber",plant2:"sunflower",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"coriander_dill",plant2:"beets",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"broccoli",plant2:"coriander_dill",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"brussell_sprouts",plant2:"coriander_dill",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"coriander_dill",plant2:"cabbages",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"coriander_dill",plant2:"carrots",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cauliflower",plant2:"coriander_dill",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"coriander_dill",plant2:"celery",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"coriander_dill",plant2:"chervil",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"coriander_dill",plant2:"coriander_dill",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"coriander_dill",plant2:"cucumber",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"coriander_dill",plant2:"fennel",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"coriander_dill",plant2:"tomato",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"eggplant",plant2:"beans",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"eggplant",plant2:"marjoram",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"eggplant",plant2:"potatoes",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"fennel",plant2:"basil",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"fennel",plant2:"beans",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"fennel",plant2:"broad_beans",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"fennel",plant2:"tomato",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"marigold",plant2:"apple",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"marigold",plant2:"apricot",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"marigold",plant2:"beans",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"broccoli",plant2:"marigold",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"brussell_sprouts",plant2:"marigold",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"marigold",plant2:"cabbages",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cauliflower",plant2:"marigold",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"marigold",plant2:"cherry",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"marigold",plant2:"fruit_trees",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"marigold",plant2:"lettuce",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"marigold",plant2:"mulberry",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"marigold",plant2:"rose",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"marigold",plant2:"strawberry",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"marigold",plant2:"tomato",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"fruit_trees",plant2:"carrots",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"fruit_trees",plant2:"chives",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"fruit_trees",plant2:"marigold",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"fruit_trees",plant2:"garlic",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"fruit_trees",plant2:"nasturtium",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"fruit_trees",plant2:"sliverbeet",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"fruit_trees",plant2:"spinach",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"fruit_trees",plant2:"stinging_nettle",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"fruit_trees",plant2:"yarrow",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"garlic",plant2:"apple",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"garlic",plant2:"apricot",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"garlic",plant2:"beans",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"garlic",plant2:"broad_beans",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"garlic",plant2:"bush_beans",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"garlic",plant2:"climbing_beans",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"garlic",plant2:"cabbages",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"garlic",plant2:"cherry",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"garlic",plant2:"fruit_trees",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"garlic",plant2:"mulberry",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"peas",plant2:"garlic",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"garlic",plant2:"rosemary",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"garlic",plant2:"rose",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"garlic",plant2:"strawberry",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"gooseberry",plant2:"tomato",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"grape_vine",plant2:"mulberry",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"grape_vine",plant2:"tomato",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"grape_vine",plant2:"yarrow",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"apple",plant2:"grass",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"grass",plant2:"apricot",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"grass",plant2:"cherry",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"grass",plant2:"fruit_trees",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"grass",plant2:"mulberry",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"grass",plant2:"sage",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"grass",plant2:"yarrow",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"horseradish",plant2:"apple",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"horseradish",plant2:"apricot",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"horseradish",plant2:"cherry",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"horseradish",plant2:"potatoes",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"horseradish",plant2:"rose",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"horseradish",plant2:"stinging_nettle",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"lavender",plant2:"cabbages",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"lavender",plant2:"fennel",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"lavender",plant2:"garlic",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"lavender",plant2:"marjoram",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"lavender",plant2:"rose",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"lavender",plant2:"sliverbeet",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"lavender",plant2:"strawberry",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"leeks",plant2:"carrots",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"leeks",plant2:"celery",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"leeks",plant2:"marjoram",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"leeks",plant2:"onions",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"lemon_balm",plant2:"apple",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"lemon_balm",plant2:"apricot",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"lemon_balm",plant2:"cherry",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"lemon_balm",plant2:"fruit_trees",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"lemon_balm",plant2:"mulberry",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"lemon_balm",plant2:"rose",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"lettuce",plant2:"beans",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"lettuce",plant2:"broad_beans",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"lettuce",plant2:"climbing_beans",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"lettuce",plant2:"beets",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"lettuce",plant2:"cabbages",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"lettuce",plant2:"carrots",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"lettuce",plant2:"cherry",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"lettuce",plant2:"chervil",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"lettuce",plant2:"cucumber",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"lettuce",plant2:"marigold",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"lettuce",plant2:"marjoram",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"lettuce",plant2:"onions",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"lettuce",plant2:"parsley",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"peas",plant2:"lettuce",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"lettuce",plant2:"radish",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"lettuce",plant2:"strawberry",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"marjoram",plant2:"asparagus",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"marjoram",plant2:"beans",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"marjoram",plant2:"broad_beans",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"marjoram",plant2:"bush_beans",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"marjoram",plant2:"climbing_beans",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"marjoram",plant2:"beets",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"broccoli",plant2:"marjoram",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"brussell_sprouts",plant2:"marjoram",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"marjoram",plant2:"cabbages",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"marjoram",plant2:"carrots",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cauliflower",plant2:"marjoram",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"marjoram",plant2:"celery",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"marjoram",plant2:"chives",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"marjoram",plant2:"corn",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"marjoram",plant2:"cucumber",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"marjoram",plant2:"lettuce",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"marjoram",plant2:"onions",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"peas",plant2:"marjoram",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"marjoram",plant2:"potatoes",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"marjoram",plant2:"pumpkin",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"marjoram",plant2:"radish",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"marjoram",plant2:"sliverbeet",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"marjoram",plant2:"spinach",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"marjoram",plant2:"squash",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"marjoram",plant2:"tomato",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"marjoram",plant2:"zucchini",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"mints",plant2:"cabbages",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"mints",plant2:"chamomile",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"mints",plant2:"parsley",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"mints",plant2:"tomato",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"mustard",plant2:"apple",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"mustard",plant2:"apricot",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"mustard",plant2:"cherry",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"mustard",plant2:"fruit_trees",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"mustard",plant2:"grape_vine",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"mustard",plant2:"mulberry",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"nasturtium",plant2:"apple",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"nasturtium",plant2:"apricot",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"broccoli",plant2:"nasturtium",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"nasturtium",plant2:"cabbages",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"nasturtium",plant2:"cherry",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"nasturtium",plant2:"cucumber",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"nasturtium",plant2:"fruit_trees",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"nasturtium",plant2:"mulberry",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"nasturtium",plant2:"potatoes",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"nasturtium",plant2:"radish",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"nasturtium",plant2:"rose",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"nasturtium",plant2:"squash",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"nasturtium",plant2:"tomato",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"nasturtium",plant2:"zucchini",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"onions",plant2:"beans",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"onions",plant2:"broad_beans",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"onions",plant2:"bush_beans",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"onions",plant2:"climbing_beans",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"onions",plant2:"beets",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"onions",plant2:"cabbages",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"onions",plant2:"carrots",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"onions",plant2:"lettuce",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"onions",plant2:"marjoram",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"onions",plant2:"parsley",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"peas",plant2:"onions",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"onions",plant2:"rose",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"onions",plant2:"savory",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"onions",plant2:"sliverbeet",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"onions",plant2:"strawberry",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"onions",plant2:"tomato",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"parsley",plant2:"asparagus",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"parsley",plant2:"beans",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"parsley",plant2:"chives",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"parsley",plant2:"lettuce",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"parsley",plant2:"onions",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"parsley",plant2:"rosemary",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"parsley",plant2:"rose",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"parsley",plant2:"tomato",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"parsnip",plant2:"beans",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"parsnip",plant2:"carrots",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"parsnip",plant2:"celery",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"parsnip",plant2:"chives",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"parsnip",plant2:"coriander_dill",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"parsnip",plant2:"corn",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"parsnip",plant2:"lettuce",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"parsnip",plant2:"marjoram",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"parsnip",plant2:"onions",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"peas",plant2:"parsnip",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"parsnip",plant2:"potatoes",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"parsnip",plant2:"radish",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"parsnip",plant2:"sage",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"parsnip",plant2:"tomato",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"potatoes",plant2:"beans",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"potatoes",plant2:"broad_beans",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"potatoes",plant2:"bush_beans",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"potatoes",plant2:"beets",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"broccoli",plant2:"potatoes",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"brussell_sprouts",plant2:"potatoes",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"potatoes",plant2:"cabbages",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cauliflower",plant2:"potatoes",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"potatoes",plant2:"celery",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"potatoes",plant2:"cherry",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"potatoes",plant2:"corn",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"potatoes",plant2:"cucumber",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"potatoes",plant2:"marigold",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"potatoes",plant2:"marjoram",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"potatoes",plant2:"nasturtium",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"peas",plant2:"potatoes",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"pumpkin",plant2:"corn",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"pumpkin",plant2:"marjoram",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"pumpkin",plant2:"potatoes",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"radish",plant2:"climbing_beans",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"radish",plant2:"carrots",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"radish",plant2:"chervil",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"radish",plant2:"corn",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"radish",plant2:"cucumber",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"radish",plant2:"lettuce",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"radish",plant2:"marjoram",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"radish",plant2:"nasturtium",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"raspberry",plant2:"marigold",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"peas",plant2:"raspberry",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"raspberry",plant2:"potatoes",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"raspberry",plant2:"rue",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"rosemary",plant2:"beans",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"rosemary",plant2:"cabbages",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"rosemary",plant2:"garlic",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"rosemary",plant2:"potatoes",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"rosemary",plant2:"sage",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"rosemary",plant2:"tomato",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"roses",plant2:"chives",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"roses",plant2:"marigold",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"roses",plant2:"garlic",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"roses",plant2:"nasturtium",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"roses",plant2:"onions",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"roses",plant2:"parsley",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"roses",plant2:"rue",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"roses",plant2:"sage",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"rue",plant2:"basil",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"broccoli",plant2:"rue",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"rue",plant2:"cabbages",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"rue",plant2:"carrots",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cauliflower",plant2:"rue",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"rue",plant2:"rose",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"rue",plant2:"sage",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"sage",plant2:"beans",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"sage",plant2:"cabbages",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"sage",plant2:"cucumber",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"peas",plant2:"sage",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"sage",plant2:"rosemary",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"sage",plant2:"rose",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"sage",plant2:"rue",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"sage",plant2:"strawberry",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"silverbeet",plant2:"basil",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"silverbeet",plant2:"beets",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"silverbeet",plant2:"cherry",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"silverbeet",plant2:"fruit_trees",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"silverbeet",plant2:"marjoram",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"silverbeet",plant2:"mulberry",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"silverbeet",plant2:"onions",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"spinach",plant2:"apple",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"spinach",plant2:"apricot",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"spinach",plant2:"broad_beans",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"spinach",plant2:"cherry",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"spinach",plant2:"fruit_trees",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"spinach",plant2:"marjoram",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"spinach",plant2:"mulberry",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"spinach",plant2:"strawberry",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"strawberry",plant2:"bush_beans",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"strawberry",plant2:"borage",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"broccoli",plant2:"strawberry",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"brussell_sprouts",plant2:"strawberry",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"strawberry",plant2:"cabbages",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cauliflower",plant2:"strawberry",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"strawberry",plant2:"chives",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"strawberry",plant2:"marigold",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"strawberry",plant2:"lettuce",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"strawberry",plant2:"onions",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"strawberry",plant2:"sage",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"strawberry",plant2:"spinach",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"sunflower",plant2:"apricot",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"sunflower",plant2:"bush_beans",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"sunflower",plant2:"climbing_beans",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"brussell_sprouts",plant2:"sunflower",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"sunflower",plant2:"cucumber",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"sunflower",plant2:"garlic",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"sunflower",plant2:"potatoes",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"sunflower",plant2:"squash",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"thyme",plant2:"cabbages",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"thyme",plant2:"rose",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"tomato",plant2:"apricot",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"tomato",plant2:"asparagus",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"tomato",plant2:"basil",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"tomato",plant2:"beets",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"tomato",plant2:"borage",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"broccoli",plant2:"tomato",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"tomato",plant2:"carrots",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"cauliflower",plant2:"tomato",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"tomato",plant2:"celery",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"tomato",plant2:"chives",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"tomato",plant2:"fennel",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"tomato",plant2:"marigold",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"tomato",plant2:"grape_vine",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"tomato",plant2:"marjoram",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"tomato",plant2:"nasturtium",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"tomato",plant2:"onions",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"tomato",plant2:"parsley",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"tomato",plant2:"potatoes",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"tomato",plant2:"rosemary",state:"bad",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"tomato",plant2:"stinging_nettle",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"yarrow",plant2:"apple",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"yarrow",plant2:"apricot",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"yarrow",plant2:"cherry",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"yarrow",plant2:"fruit_trees",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"yarrow",plant2:"grape_vine",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"yarrow",plant2:"mulberry",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"zucchini",plant2:"corn",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"zucchini",plant2:"marjoram",state:"good",comment:"Wow, I mean really this is really long and stuff"},
	{plant1:"zucchini",plant2:"nasturtium",state:"good",comment:"Wow, I mean really this is really long and stuff"}
];


